export const siteConfig = {
  name: "Georgian Royal Wine",
  shortName: "GRW",
  url: "https://grw-wine.com",
  locale: "es_ES",
  phone: "+34607609474",
  phoneDisplay: "+34 607 609 474",
  email: "sbs@sb-servicio.com",
  streetAddress: "Calle Paseo Vistalegre nº8, 6º derecha",
  addressLocality: "Torrevieja",
  addressRegion: "Alicante",
  postalCode: "03181",
  addressCountry: "ES",
  geo: {
    latitude: 37.9787,
    longitude: -0.6822,
  },
  instagram: "https://www.instagram.com/georgianwine.es",
  defaultTitle:
    "Comprar vino online en España | Georgian Royal Wine — Torrevieja",
  defaultDescription:
    "Compra vino online en España — tienda en Torrevieja (Costa Blanca). Vinos premium georgianos y envío a Madrid, Barcelona, Marbella, Valencia, Málaga y toda España. Saperavi, Kindzmarauli, Mukuzani, Khvanchkara, qvevri y Rezo's Wine. Entrega gratis a partir de 1 caja.",
  keywords: [
    // How clients actually search (general wine Spain)
    "comprar vino online España",
    "tienda de vinos España",
    "tienda de vino online",
    "mejor vino España",
    "mejores vinos de España",
    "vinos premium España",
    "vino de calidad España",
    "comprar vino tinto España",
    "vino tinto bueno",
    "vino blanco premium",
    "vino para regalar",
    "caja de vino online",
    "envio vino a domicilio",
    "entrega vino a domicilio España",
    "envio vino España",
    "envio gratis vino España",
    "wine delivery Spain",
    "buy wine online Spain",
    "best wine in Spain",
    "best wine shop Spain",
    "wine shop Spain",
    "online wine store Spain",
    // Local / city intent
    "tienda de vinos Torrevieja",
    "tienda de vino Torrevieja",
    "comprar vino Torrevieja",
    "vino Torrevieja",
    "bodega Torrevieja",
    "entrega vino Torrevieja",
    "vino Costa Blanca",
    "tienda vino Alicante",
    "vino Alicante",
    "comprar vino Madrid",
    "tienda de vinos Madrid",
    "comprar vino Barcelona",
    "tienda de vinos Barcelona",
    "comprar vino Marbella",
    "tienda de vinos Marbella",
    "vino Valencia online",
    "vino Málaga online",
    "vino Benidorm",
    "wine shop Torrevieja",
    "wine store Costa Blanca",
    "wine delivery Madrid",
    "wine delivery Barcelona",
    // Georgian / brand (kept from before + specialty)
    "vino georgiano",
    "vino de Georgia",
    "vinos georgianos",
    "vino georgiano España",
    "comprar vino georgiano",
    "comprar vino Georgia",
    "tienda vino georgiano",
    "vino georgiano online",
    "bodega georgiana España",
    "vino georgiano Torrevieja",
    "vino georgiano Madrid",
    "vino georgiano Barcelona",
    "vino georgiano Marbella",
    "vino georgiano Valencia",
    "vino georgiano Málaga",
    "vino georgiano Benidorm",
    "Saperavi",
    "Saperavi España",
    "Kindzmarauli",
    "Khvanchkara",
    "Mukuzani",
    "Tsinandali",
    "vino qvevri",
    "qvevri wine",
    "vino ámbar Georgia",
    "Rezo's Wine",
    "GRW wine",
    "Georgian Royal Wine",
    "Georgian wine Spain",
    "Georgian wine Torrevieja",
    "Georgian wine Madrid",
    "Georgian wine Barcelona",
    "Georgian wine Marbella",
    "buy Georgian wine Spain",
    "Georgian wine shop Spain",
    // Russian-speaking clients in Spain
    "купить вино Испания",
    "магазин вина Торревьеха",
    "доставка вина Испания",
    "хорошее вино Испания",
    "лучшее вино Испания",
    "грузинское вино Испания",
    "грузинское вино Торревьеха",
    "купить грузинское вино Испания",
    "Саперави Испания",
    "Киндзмараули Испания",
    "Хванчкара",
  ],
} as const;

export function absoluteUrl(path = "/") {
  const base = siteConfig.url.replace(/\/$/, "");
  if (!path || path === "/") return base;
  return `${base}${path.startsWith("/") ? path : `/${path}`}`;
}
